---
title: "Russia Strong"
author: "Daniel Shapiro"
date: "9/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(scipen = 999)
library(tidyverse)
library(readxl)
library(gt)
library(scales)
```

```{r read}
strength <- read_xlsx("raw-data/strong.xlsx") %>% select(-c(`Pct Change`, Country))
strength$Value <- prettyNum(strength$Value, big.mark = ",")

nat_pwr <- read_xlsx("raw-data/national_power.xlsx") %>% select(-c(`Pct Change`, Statistic))
nat_pwr$Value <- prettyNum(nat_pwr$Value, big.mark = ",")

strength <- pivot_wider(strength, names_from = Year, values_from = Value) %>%
  mutate(`Pct Change` = c(-0.07/100, 1.34/100, 4.49/100, -1.13/100, -1.55/100, 0.94/100, -0.43/100, -0.54/100, -4.49/100, -0.97/100, -0.59/100, -0.77/100
))

strength$`2018` <- as.numeric(gsub(",","",strength$`2018`,fixed=TRUE))
strength$`2019` <- as.numeric(gsub(",","",strength$`2019`,fixed=TRUE)) 

nat_pwr <- pivot_wider(nat_pwr, names_from = Year, values_from = Value) %>%
  mutate(`Pct Change` = c(-0.27/100, -9.96/100, 0.39/100, 0.27/100, -0.91/100, 0.93/100, 1.33/100, -1.11/100, -2.01/100, 0.66/100, 0.31/100))

nat_pwr$`2018` <- as.numeric(gsub(",","",nat_pwr$`2018`,fixed=TRUE))
nat_pwr$`2019` <- as.numeric(gsub(",","",nat_pwr$`2019`,fixed=TRUE))
```

```{r gtstrength}
gt <- gt(strength)

gt <- gt %>% fmt_percent(columns = vars(`Pct Change`)) %>%
  fmt_number(columns = vars(`2018`), drop_trailing_zeros = TRUE) %>%
  fmt_number(columns = vars(`2019`), drop_trailing_zeros = TRUE) %>%
  fmt_percent(columns = vars(`2018`), rows = 4:12) %>%
  fmt_percent(columns = vars(`2019`), rows = 4:12)  %>%
  tab_spanner(label = "Year", columns = vars(`2018`, `2019`)) %>%
  tab_header(title = "Russian National Power Components, 2018-2019",
             subtitle = "Formula from Taiwanese scholar Chin-Lung Chang")

gt
```

```{r gt2}
gt2 <- gt(nat_pwr) %>%
  fmt_percent(columns = vars(`Pct Change`)) %>%
  tab_spanner(label = "Year", columns = vars(`2018`, `2019`)) %>%
  tab_header(title = "Comparative Change in National Power, 2018-2019",
             subtitle = "Formula from Taiwanese Scholar Chin-Lung Chang") %>%
  tab_style(style = 
              cell_text(weight = "bold"),
            locations = cells_data(columns = vars(Country, `2018`, `2019`, `Pct Change`), 
                                   rows = 1
                                   ))
gt2
```

